// Generated by Framer (7c2f7bf)
import {
    addPropertyControls as e,
    ControlType as t,
    QueryEngine as l
} from "framer";
import {
    DatabaseCollection as r,
    DatabaseDictionaryIndex as a
} from "./xh1LtkXB8-0.js";
import {
    getRichTextJsonResolver as o
} from "./xh1LtkXB8-1.js";
let i = {
        c4LtgZhSX: {
            isNullable: !0,
            type: t.Enum
        },
        createdAt: {
            isNullable: !0,
            type: t.Date
        },
        id: {
            isNullable: !1,
            type: t.String
        },
        nextItemId: {
            isNullable: !0,
            type: t.String
        },
        O2l_vcg1P: {
            isNullable: !0,
            type: t.Boolean
        },
        oQdBtKrcK: {
            isNullable: !0,
            type: t.String
        },
        p5peP8ErJ: {
            isNullable: !0,
            type: t.Date
        },
        previousItemId: {
            isNullable: !0,
            type: t.String
        },
        Rd6j4GOOr: {
            isNullable: !0,
            type: t.String
        },
        updatedAt: {
            isNullable: !0,
            type: t.Date
        },
        vbtLBmZr2: {
            isNullable: !0,
            type: t.RichText
        },
        xDjjiIyrc: {
            isNullable: !0,
            type: t.ResponsiveImage
        },
        yaNLAN1hN: {
            isNullable: !0,
            type: t.String
        }
    },
    m = ["id"],
    c = {
        type: 1
    },
    n = ["previousItemId"],
    d = ["nextItemId"],
    u = ["id", "oQdBtKrcK"],
    s = ["oQdBtKrcK", "id"],
    f = ["yaNLAN1hN"],
    p = {
        type: 0
    },
    y = ["O2l_vcg1P"],
    h = ["Rd6j4GOOr"],
    g = ["xDjjiIyrc"],
    L = ["p5peP8ErJ"],
    x = ["c4LtgZhSX"],
    w = ["vbtLBmZr2"],
    N = ["oQdBtKrcK"],
    B = [],
    S = e => {
        let t = B[e];
        if (t) return t().then(e => e.default);
    },
    I = {},
    X = o(I),
    R = new l,
    k = {
        collectionByLocaleId: {
            default: new r({
                chunks: [new URL("./xh1LtkXB8-chunk-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")],
                id: "dff1d431-c276-4e47-b07c-4780a1fa9334default",
                indexes: [new a({
                    collation: c,
                    collectionSchema: i,
                    fieldNames: m,
                    range: {
                        from: 0,
                        to: 265
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: i,
                    fieldNames: n,
                    range: {
                        from: 265,
                        to: 529
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: i,
                    fieldNames: d,
                    range: {
                        from: 529,
                        to: 789
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: i,
                    fieldNames: u,
                    range: {
                        from: 789,
                        to: 1536
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: c,
                    collectionSchema: i,
                    fieldNames: s,
                    range: {
                        from: 1536,
                        to: 2283
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: f,
                    range: {
                        from: 2283,
                        to: 2861
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: y,
                    range: {
                        from: 2861,
                        to: 3013
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: h,
                    range: {
                        from: 3013,
                        to: 4809
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: g,
                    range: {
                        from: 4809,
                        to: 10021
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: L,
                    range: {
                        from: 10021,
                        to: 10243
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: x,
                    range: {
                        from: 10243,
                        to: 10515
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: w,
                    range: {
                        from: 10515,
                        to: 82257
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: i,
                    fieldNames: N,
                    range: {
                        from: 82257,
                        to: 82858
                    },
                    url: new URL("./xh1LtkXB8-indexes-default-0.framercms", "https://framerusercontent.com/modules/wqbzfZhAQOCLXCGwDfa1/KMNQNUluyKn5NV1OYFTA/xh1LtkXB8.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: X,
                resolveVectorSetItem: S,
                schema: i
            })
        },
        displayName: "Blog",
        id: "dff1d431-c276-4e47-b07c-4780a1fa9334"
    };
export default k;
e(k, {
    yaNLAN1hN: {
        defaultValue: "",
        title: "Title",
        type: t.String
    },
    O2l_vcg1P: {
        defaultValue: !1,
        title: "Featured",
        type: t.Boolean
    },
    Rd6j4GOOr: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Short Description",
        type: t.String
    },
    xDjjiIyrc: {
        title: "Main Image",
        type: t.ResponsiveImage
    },
    p5peP8ErJ: {
        title: "Date",
        type: t.Date
    },
    c4LtgZhSX: {
        defaultValue: "rgdzslZw4",
        options: ["rgdzslZw4", "zfuyOMywP", "XD3vl_7Ke", "vu0_mHTCC"],
        optionTitles: ["Psychology", "Strategy", "Trends", "Process"],
        title: "Category",
        type: t.Enum
    },
    vbtLBmZr2: {
        defaultValue: "",
        title: "Content",
        type: t.RichText
    },
    oQdBtKrcK: {
        preventLocalization: !1,
        title: "Slug",
        type: t.String
    },
    createdAt: {
        title: "Created",
        type: t.Date
    },
    updatedAt: {
        title: "Updated",
        type: t.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/xh1LtkXB8:default",
        title: "Previous",
        type: t.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/xh1LtkXB8:default",
        title: "Next",
        type: t.CollectionReference
    }
});
export const c4LtgZhSXToDisplayName = (e, t) => {
    switch (t ?.fallback, e) {
        case "rgdzslZw4":
            return "Psychology";
        case "zfuyOMywP":
            return "Strategy";
        case "XD3vl_7Ke":
            return "Trends";
        case "vu0_mHTCC":
            return "Process";
        default:
            return "";
    }
};
export const enumToDisplayNameFunctions = {
    c4LtgZhSX: c4LtgZhSXToDisplayName
};
export const utils = {
    async getSlugByRecordId(e, t) {
        let [l] = await R.query({
            from: {
                data: k,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "oQdBtKrcK",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t);
        return l ?.oQdBtKrcK;
    },
    async getRecordIdBySlug(e, t) {
        let [l] = await R.query({
            from: {
                data: k,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "oQdBtKrcK",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t);
        return l ?.id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "c4LtgZhSXToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerContractVersion": "1",
                "framerRecordIdKey": "id",
                "framerColorSyntax": "false",
                "framerSlug": "oQdBtKrcK",
                "framerAutoSizeImages": "true",
                "framerCollectionId": "xh1LtkXB8",
                "framerCollectionUtils": "1",
                "framerData": "true",
                "framerEnumToDisplayNameUtils": "2"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}