// Generated by Framer (571faa6)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = 'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 24C5.373 24 0 18.627 0 12S5.373 0 12 0s12 5.373 12 12-5.373 12-12 12zm0-22C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zm6.208 15.657l-7.792-10.457H8.792v9.596h1.5v-7.39l6.564 8.784 1.352-1.533zM16.5 16.2h-1.5V7.2h1.5v9z" fill="var(--12auh5f, var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0)))"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    color,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        zZ3sDiGC9: color ?? props.zZ3sDiGC9 ?? "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        zZ3sDiGC9,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-izx7y", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--12auh5f": zZ3sDiGC9,
            ...style
        }
    });
});
const css = [`.framer-izx7y { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--12auh5f); mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"zZ3sDiGC9":"color"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Next.js","color":{"type":"variable","value":"12auh5f"},"set":{"localId":"vectorSet/zWcoFJGye","id":"zWcoFJGye","moduleId":"foi8KRYmiUbaVeWDl4ta"}}
 */
const Icon = withCSS(Component, css, "framer-izx7y");
Icon.displayName = "Next.js";
export default Icon;
addPropertyControls(Icon, {
    zZ3sDiGC9: {
        defaultValue: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVariables": "{\"zZ3sDiGC9\":\"color\"}",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerContractVersion": "1",
                "framerVector": "{\"name\":\"Next.js\",\"color\":{\"type\":\"variable\",\"value\":\"12auh5f\"},\"set\":{\"localId\":\"vectorSet/zWcoFJGye\",\"id\":\"zWcoFJGye\",\"moduleId\":\"foi8KRYmiUbaVeWDl4ta\"}}",
                "framerIntrinsicHeight": "24",
                "framerIntrinsicWidth": "24",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}