// Generated by Framer (02004a2)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const serializationHash = "framer-ofAMn";
const variantClassNames = {
    wbh2tnLAE: "framer-v-1gob8wf"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const De9UXQuLp = undefined;
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .6,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ?? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    image,
    width,
    ...props
}) => {
    return { ...props,
        De9UXQuLp: image ?? props.De9UXQuLp ?? {
            pixelHeight: 64,
            pixelWidth: 64,
            src: "https://framerusercontent.com/images/pKKKvDTDIMbGXt4SKNGc5PEgrkU.jpg?width=64&height=64"
        }
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ?? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        De9UXQuLp,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "wbh2tnLAE",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ?? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Image, { ...restProps,
                    ...gestureHandlers,
                    background: {
                        alt: "Headshot of *Designer Name*",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(componentViewport ?.y || 0),
                        pixelHeight: 64,
                        pixelWidth: 64,
                        sizes: componentViewport ?.width || "100vw",
                        ...toResponsiveImage(De9UXQuLp),
                        ...{
                            positionX: "center",
                            positionY: "center"
                        }
                    },
                    className: cx(scopingClassNames, "framer-1gob8wf", className, classNames),
                    "data-framer-name": "default",
                    layoutDependency: layoutDependency,
                    layoutId: "wbh2tnLAE",
                    ref: refBinding,
                    style: {
                        borderBottomLeftRadius: 1e3,
                        borderBottomRightRadius: 1e3,
                        borderTopLeftRadius: 1e3,
                        borderTopRightRadius: 1e3,
                        ...style
                    }
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ofAMn.framer-lxsivx, .framer-ofAMn .framer-lxsivx { display: block; }", ".framer-ofAMn.framer-1gob8wf { height: 32px; overflow: visible; position: relative; width: 32px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"De9UXQuLp":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerQHsZGkb1s = withCSS(Component, css, "framer-ofAMn");
export default FramerQHsZGkb1s;
FramerQHsZGkb1s.displayName = "Profile Picture";
FramerQHsZGkb1s.defaultProps = {
    height: 32,
    width: 32
};
addPropertyControls(FramerQHsZGkb1s, {
    De9UXQuLp: {
        __defaultAssetReference: "data:framer/asset-reference,pKKKvDTDIMbGXt4SKNGc5PEgrkU.jpg?originalFilename=avatar3.jpg&preferredSize=auto",
        title: "Image",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramerQHsZGkb1s, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerQHsZGkb1s",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerVariables": "{\"De9UXQuLp\":\"image\"}",
                "framerIntrinsicHeight": "32",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicWidth": "32",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./QHsZGkb1s.map