// Generated by Framer (27b79d7)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1ljqpfr",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "l7oqt8",
            mediaQuery: "(min-width: 992px) and (max-width: 1199.98px)"
        }, {
            hash: "kqawv6",
            mediaQuery: "(min-width: 768px) and (max-width: 991.98px)"
        }, {
            hash: "hvpvjs",
            mediaQuery: "(max-width: 767.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {},
        robots: "max-image-preview:large",
        serializationId: "framer-DRb42",
        title: siteMetadata(params, activeLocale).title || "Projects",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}