// Generated by Framer (7e4cc89)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-n1Byv .framer-styles-preset-1x5k5dq:not(.rich-text-wrapper), .framer-n1Byv .framer-styles-preset-1x5k5dq.rich-text-wrapper a { --framer-link-current-text-color: var(--token-e3a90888-763b-420f-bb27-f2520e07d9b1, #dedede); --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-46244ad7-86a7-41b8-b44b-214d95b54c13, #828282); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-33c8dbd0-eb94-4e90-8099-e7a3fee4ad2f, #ffffff); --framer-link-text-decoration: none; transition: color 0.4s cubic-bezier(0.44, 0, 0.56, 1) 0s; }"];
export const className = "framer-n1Byv";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}