// Generated by Framer (27b79d7)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "4o26ew",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "k8hute",
            mediaQuery: "(min-width: 992px) and (max-width: 1199.98px)"
        }, {
            hash: "1fxqx9d",
            mediaQuery: "(min-width: 768px) and (max-width: 991.98px)"
        }, {
            hash: "uax692",
            mediaQuery: "(max-width: 767.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {},
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-dsvr8",
        title: siteMetadata(params, activeLocale).title || "Terms",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}