// Generated by Framer (e56d21e)
import siteMetadata from "#framer/local/siteMetadata/siteMetadata/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1qi8g8n",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "15s7ov1",
            mediaQuery: "(min-width: 992px) and (max-width: 1199.98px)"
        }, {
            hash: "tqkk05",
            mediaQuery: "(min-width: 768px) and (max-width: 991.98px)"
        }, {
            hash: "62h186",
            mediaQuery: "(max-width: 767.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {},
        robots: "max-image-preview:large",
        serializationId: "framer-YBSnm",
        title: siteMetadata(params, activeLocale).title || "Blog",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}