// Generated by Framer (571faa6)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = 'url(\'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 16 0 L 16 8 L 8 8 Z M 0 8 L 8 8 L 16 16 L 0 16 Z M 0 16 L 8 16 L 8 24 Z" fill="var(--12auh5f, var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0)))" height="24px" id="cRzu_KaKs" transform="translate(4 0)" width="16px"/></svg>\') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)';
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    color,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        zZ3sDiGC9: color ?? props.zZ3sDiGC9 ?? "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        zZ3sDiGC9,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-Ezrn8", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--12auh5f": zZ3sDiGC9,
            ...style
        }
    });
});
const css = [`.framer-Ezrn8 { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--12auh5f); mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"zZ3sDiGC9":"color"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Framer","color":{"type":"variable","value":"12auh5f"},"set":{"localId":"vectorSet/zWcoFJGye","id":"zWcoFJGye","moduleId":"foi8KRYmiUbaVeWDl4ta"}}
 */
const Icon = withCSS(Component, css, "framer-Ezrn8");
Icon.displayName = "Framer";
export default Icon;
addPropertyControls(Icon, {
    zZ3sDiGC9: {
        defaultValue: "var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, rgb(0, 0, 0))",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerIntrinsicWidth": "24",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVariables": "{\"zZ3sDiGC9\":\"color\"}",
                "framerIntrinsicHeight": "24",
                "framerVector": "{\"name\":\"Framer\",\"color\":{\"type\":\"variable\",\"value\":\"12auh5f\"},\"set\":{\"localId\":\"vectorSet/zWcoFJGye\",\"id\":\"zWcoFJGye\",\"moduleId\":\"foi8KRYmiUbaVeWDl4ta\"}}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}