// Generated by Framer (6ca5d98)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z" fill="transparent" stroke="var(--21h8s6, rgb(0, 0, 0))" stroke-width="var(--pgex8v, 1.5)" stroke-linejoin="round" stroke-linecap="round"/><path d="M20 3v4" fill="transparent" stroke="var(--21h8s6, rgb(0, 0, 0))" stroke-width="var(--pgex8v, 1.5)" stroke-linejoin="round" stroke-linecap="round"/><path d="M22 5h-4" fill="transparent" stroke="var(--21h8s6, rgb(0, 0, 0))" stroke-width="var(--pgex8v, 1.5)" stroke-linejoin="round" stroke-linecap="round"/><path d="M4 17v2" fill="transparent" stroke="var(--21h8s6, rgb(0, 0, 0))" stroke-width="var(--pgex8v, 1.5)" stroke-linejoin="round" stroke-linecap="round"/><path d="M5 18H3" fill="transparent" stroke="var(--21h8s6, rgb(0, 0, 0))" stroke-width="var(--pgex8v, 1.5)" stroke-linejoin="round" stroke-linecap="round"/></svg>';
const getProps = ({
    alpha,
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
        lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
        qxTvv_EBh: alpha ?? props.qxTvv_EBh
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        lschgej4H,
        qxTvv_EBh,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("2403020249", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-6wimp", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m6trwb": qxTvv_EBh,
            "--21h8s6": ezTt3ayMo,
            "--pgex8v": lschgej4H,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-6wimp { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Paint Bucket","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-6wimp");
Icon.displayName = "Paint Bucket";
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    lschgej4H: {
        defaultValue: 1.5,
        displayStepper: true,
        hidden: false,
        max: 6,
        min: 0,
        step: .5,
        title: "Width",
        type: ControlType.Number
    },
    qxTvv_EBh: {
        defaultValue: 0,
        displayStepper: true,
        hidden: false,
        max: 1,
        min: 0,
        step: .1,
        title: "Alpha",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerDisableUnlink": "true",
                "framerIntrinsicWidth": "24",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"ezTt3ayMo\":\"color\",\"lschgej4H\":\"width1\",\"qxTvv_EBh\":\"alpha\"}",
                "framerIntrinsicHeight": "24",
                "framerVector": "{\"name\":\"Paint Bucket\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerContractVersion": "1",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerSupportedLayoutHeight": "any-prefer-fixed"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}