// Generated by Framer (7e4cc89)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-9TJIk .framer-styles-preset-1pmp3vy:not(.rich-text-wrapper), .framer-9TJIk .framer-styles-preset-1pmp3vy.rich-text-wrapper a { --framer-link-current-text-color: var(--token-994646e0-68ea-49d7-897a-104048558f6f, #545454); --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-46244ad7-86a7-41b8-b44b-214d95b54c13, #6b7280); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-2759885a-0605-4b0d-ae5f-9a938c3766f2, #000000); --framer-link-text-decoration: none; transition: color 0.3s cubic-bezier(0.44, 0, 0.56, 1) 0s; }"];
export const className = "framer-9TJIk";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}